/**
 * The phase table, in one place, derived from the generated constants so the
 * README, the CLI and the program can never disagree.
 */

import * as C from "./constants.ts";
import { fmt } from "./curve.ts";

export interface PhaseRow {
  ordinal: number;
  name: string;
  supplyRange: string;
  curve: string;
  walletCap: string;
  cooldown: string;
  buyFee: string;
  sellFee: string;
  triggers: string;
  changes: string;
}

const sol = (lamports: bigint) => `${Number(lamports) / 1e9} SOL`;

export const PHASE_TABLE: PhaseRow[] = [
  {
    ordinal: 0,
    name: "Seeding",
    supplyRange: `0 – ${fmt(C.P0_END)}`,
    curve: `p(s) = ${Number(C.B0) / 1e9} + ${Number(C.M0) / 1e9} * s  (lamports/token)`,
    walletCap: `${fmt(C.P0_WALLET_CAP)} tokens`,
    cooldown: `${C.P0_BUY_COOLDOWN_SLOTS} slots`,
    buyFee: `${C.BASE_BUY_FEE_BPS} bps + snipe tax up to ${C.SNIPE_TAX_MAX_BPS} bps, decaying over ${C.SNIPE_TAX_SLOTS} slots`,
    sellFee: `${C.BASE_SELL_FEE_BPS} -> ${C.MIN_SELL_FEE_BPS} bps over ${C.MATURE_SLOTS} slots of tenure`,
    triggers: `supply >= ${fmt(C.P0_END)} OR holders >= ${C.P0_HOLDER_TRIGGER} OR age >= ${C.P0_TIME_TRIGGER_SLOTS} slots`,
    changes: "tight caps and a long cooldown; the snipe tax is at its peak",
  },
  {
    ordinal: 1,
    name: "Discovery",
    supplyRange: `${fmt(C.P0_END)} – ${fmt(C.P1_END)}`,
    curve: `p(s) = ${Number(C.B1) / 1e9} + ${Number(C.M1) / 1e9} * (s - ${fmt(C.P0_END)})`,
    walletCap: `${fmt(C.P1_WALLET_CAP)} tokens`,
    cooldown: `${C.P1_BUY_COOLDOWN_SLOTS} slots`,
    buyFee: `${C.BASE_BUY_FEE_BPS} bps (snipe tax has decayed)`,
    sellFee: "same tenure schedule, plus the transition guard",
    triggers: `supply >= ${fmt(C.P1_END)} OR volume >= ${sol(C.P1_VOLUME_TRIGGER_LAMPORTS)} OR tenure-weighted holder vote`,
    changes: `caps widen 4x, cooldown drops to ${C.P1_BUY_COOLDOWN_SLOTS} slots, slope steepens`,
  },
  {
    ordinal: 2,
    name: "Acceleration",
    supplyRange: `${fmt(C.P1_END)} – ${fmt(C.P2_END)}`,
    curve: `p(s) = ${Number(C.B2) / 1e9} + ${Number(C.M2) / 1e9} * (s - ${fmt(C.P1_END)})`,
    walletCap: "none",
    cooldown: "none",
    buyFee: `${C.BASE_BUY_FEE_BPS} bps`,
    sellFee: "same tenure schedule, plus the transition guard",
    triggers: `supply >= ${fmt(C.P2_END)} (graduation threshold)`,
    changes: "caps and cooldowns lift entirely; the steepest slope runs",
  },
  {
    ordinal: 3,
    name: "Graduating",
    supplyRange: `${fmt(C.P2_END)}`,
    curve: "frozen",
    walletCap: "n/a",
    cooldown: "n/a",
    buyFee: "curve closed",
    sellFee: "curve closed",
    triggers: "anyone calls `graduate` (permissionless)",
    changes: "reserve moves to the locked pool, LP is minted, mint authority is revoked",
  },
  {
    ordinal: 4,
    name: "Perpetual",
    supplyRange: `capped at ${fmt(C.P2_END + C.LP_SUPPLY)}`,
    curve: `constant product, ${C.POOL_FEE_BPS} bps fee (${C.POOL_FEE_MATURED_BPS} bps for matured holders)`,
    walletCap: "none",
    cooldown: "none",
    buyFee: `${C.POOL_FEE_BPS} bps`,
    sellFee: `${C.POOL_FEE_BPS} bps`,
    triggers: "terminal — the fee flywheel runs forever",
    changes: `every ${C.FLYWHEEL_INTERVAL_SLOTS} slots anyone may crank: ${C.DEFAULT_BUYBACK_BPS / 100n}% buyback-and-burn, the rest to tenured holders`,
  },
];

export function renderPhaseTable(): string {
  const cols: [keyof PhaseRow, string][] = [
    ["name", "Phase"],
    ["supplyRange", "Tokens sold"],
    ["curve", "Curve"],
    ["walletCap", "Wallet cap"],
    ["cooldown", "Buy cooldown"],
    ["buyFee", "Buy fee"],
    ["sellFee", "Sell fee"],
    ["triggers", "Advances when"],
  ];
  return PHASE_TABLE.map((row) =>
    [
      `\n  PHASE ${row.ordinal} — ${row.name.toUpperCase()}`,
      ...cols.slice(1).map(([key, label]) => `    ${label.padEnd(14)} ${row[key]}`),
      `    ${"What changes".padEnd(14)} ${row.changes}`,
    ].join("\n"),
  ).join("\n");
}

/** Markdown table for the README, generated by `npm run docs:table`. */
export function markdownPhaseTable(): string {
  const header =
    "| Phase | Tokens sold | Curve `p(s)` lamports/token | Wallet cap | Buy cooldown | Buy fee | Sell fee | Advances when |";
  const sep = "|---|---|---|---|---|---|---|---|";
  const rows = PHASE_TABLE.map(
    (r) =>
      `| **${r.ordinal} ${r.name}** | ${r.supplyRange} | \`${r.curve}\` | ${r.walletCap} | ${r.cooldown} | ${r.buyFee} | ${r.sellFee} | ${r.triggers} |`,
  );
  return [header, sep, ...rows].join("\n");
}
